#!/bin/bash -e

##
# Set up ecomdev testing for MageLog
#

##
# Drop any existing tables without needing to drop the database.
dropAllTables() {
	local IFS=$'\n'
	tables=( $(mysql --skip-column-names jenkins_mage_log -e 'show tables;') )
	IFS=';'
	mysql jenkins_mage_log <<< "SET FOREIGN_KEY_CHECKS = 0;${tables[*]/#/DROP TABLE IF EXISTS };SET FOREIGN_KEY_CHECKS = 1;"
}
dropAllTables

# Fetch Magento ee and untar it.
mv magento magento.deleteme && rm -r magento.deleteme &
	tar -xJpf /usr/local/share/magento-1.14.0.1.tar.xz

# Checkout EcomDev submodules prior to deploy - composer doesn't play nice w/ submodules
cd vendor/ivanchepurnyi/ecomdev_phpunit && git submodule init && git submodule update && cd -

# Update dependencies
vendor/bin/composerCommandIntegrator.php magento-module-deploy

cd magento
# Run the Magento installer.
php -f install.php -- \
	--admin_frontname 'admin' \
	--admin_email 'foo@bar.com' \
	--admin_firstname 'First' \
	--admin_lastname 'Last' \
	--admin_password 'testing123' \
	--admin_username 'admin' \
	--db_host 'localhost' \
	--db_name 'jenkins_mage_log' \
	--db_pass "$(sed -n 's/password=//p' "$HOME/.my.cnf")" \
	--db_user 'jenkins' \
	--default_currency 'USD' \
	--license_agreement_accepted 'yes' \
	--locale 'en_US' \
	--secure_base_url 'https://example.com' \
	--session_save 'files' \
	--timezone 'America/New_York' \
	--url 'http://example.com' \
	--use_rewrites 'yes' \
	--use_secure 'yes' \
	--use_secure_admin 'yes' \
	--skip_url_validation 'yes'

# Set up the phpunit configurations
# Configs must be in place before EcomDev
cp ../vendor/ebayenterprise/magento-log/tests/local.xml.phpunit app/etc # Magento configuration
cp ../vendor/ebayenterprise/magento-log/tests/phpunit.xml.dist . # PHPUnit configuration

# Run phpunit
../vendor/bin/phpunit "$@" # This argument list should usually be empty, but can be switched to --debug or other flags for quick checks. Such as when phpunit suddenly starts segfaulting on Jenkins.
